import { createClient } from "@supabase/supabase-js";
import { NextResponse } from "next/server";

const VAT_THRESHOLD = 90000;

type VatCategory =
  | "standard_rated"
  | "reduced_rated"
  | "zero_rated"
  | "exempt"
  | "out_of_scope";

type MonthBucket = {
  month_label: string;
  month_key: string;
  standard_rated: number;
  reduced_rated: number;
  zero_rated: number;
  exempt: number;
  out_of_scope: number;
};

type XeroLineItem = {
  LineAmount?: number;
  TaxType?: string;
};

type XeroInvoice = {
  InvoiceID?: string;
  Type?: string;
  Status?: string;
  DateString?: string;
  Date?: string;
  LineItems?: XeroLineItem[];
};

function formatMonthLabel(date: Date) {
  return date.toLocaleString("en-GB", {
    month: "short",
    year: "numeric",
  });
}

function monthKey(date: Date) {
  return `${date.getFullYear()}-${String(date.getMonth() + 1).padStart(2, "0")}`;
}

function getLastCompleted12Months(): MonthBucket[] {
  const today = new Date();
  const endMonth = new Date(today.getFullYear(), today.getMonth() - 1, 1);

  return Array.from({ length: 12 }, (_, index) => {
    const monthDate = new Date(
      endMonth.getFullYear(),
      endMonth.getMonth() - (11 - index),
      1
    );

    return {
      month_label: formatMonthLabel(monthDate),
      month_key: monthKey(monthDate),
      standard_rated: 0,
      reduced_rated: 0,
      zero_rated: 0,
      exempt: 0,
      out_of_scope: 0,
    };
  });
}

function classifyTaxType(taxType: string | undefined): VatCategory {
  const value = String(taxType || "").toUpperCase();

  if (value === "NONE") return "standard_rated";
  if (value.includes("ZERO") || value.includes("ZERORATED")) return "zero_rated";
  if (value.includes("EXEMPT")) return "exempt";
  if (value.includes("REDUCED")) return "reduced_rated";

  return "standard_rated";
}

async function refreshXeroToken(refreshToken: string) {
  const response = await fetch("https://identity.xero.com/connect/token", {
    method: "POST",
    headers: {
      Authorization:
        "Basic " +
        Buffer.from(
          `${process.env.XERO_CLIENT_ID}:${process.env.XERO_CLIENT_SECRET}`
        ).toString("base64"),
      "Content-Type": "application/x-www-form-urlencoded",
    },
    body: new URLSearchParams({
      grant_type: "refresh_token",
      refresh_token: refreshToken,
    }),
  });

  if (!response.ok) {
    throw new Error(await response.text());
  }

  return response.json();
}

async function xeroFetch(url: string, accessToken: string, tenantId: string) {
  return fetch(url, {
    headers: {
      Authorization: `Bearer ${accessToken}`,
      "Xero-tenant-id": tenantId,
      Accept: "application/json",
    },
  });
}

async function sendVatAlertEmail(params: {
  clientName: string;
  turnover: number;
  percent: number;
  alertType: string;
  message: string;
}) {
  const apiKey = process.env.RESEND_API_KEY;
  const to = process.env.VAT_ALERT_EMAIL_TO;
  const from = process.env.VAT_ALERT_EMAIL_FROM || "VAT Checker <onboarding@resend.dev>";

  if (!apiKey || !to) {
    return { sent: false, reason: "Missing Resend environment variables" };
  }

  const response = await fetch("https://api.resend.com/emails", {
    method: "POST",
    headers: {
      Authorization: `Bearer ${apiKey}`,
      "Content-Type": "application/json",
    },
    body: JSON.stringify({
      from,
      to,
      subject: `VAT alert: ${params.clientName} - ${params.alertType}`,
      html: `
        <h2>VAT threshold alert</h2>
        <p><strong>Client:</strong> ${params.clientName}</p>
        <p><strong>Alert:</strong> ${params.alertType}</p>
        <p><strong>Rolling taxable turnover:</strong> £${params.turnover.toLocaleString()}</p>
        <p><strong>Threshold used:</strong> ${params.percent.toFixed(1)}%</p>
        <p>${params.message}</p>
        <p style="color:#666;font-size:12px;">Generated by VAT Checker from Maddock & Co.</p>
      `,
    }),
  });

  if (!response.ok) {
    return { sent: false, reason: await response.text() };
  }

  return { sent: true, reason: "Email sent" };
}

export async function GET(request: Request) {
  const url = new URL(request.url);
  const clientId = url.searchParams.get("clientId");

  if (!clientId) {
    return NextResponse.json({ error: "Missing clientId" }, { status: 400 });
  }

  const supabase = createClient(
    process.env.NEXT_PUBLIC_SUPABASE_URL!,
    process.env.SUPABASE_SERVICE_ROLE_KEY!
  );

  const { data: client } = await supabase
    .from("clients")
    .select("id,name")
    .eq("id", clientId)
    .single();

  const { data: connection, error: connectionError } = await supabase
    .from("accounting_connections")
    .select("*")
    .eq("client_id", clientId)
    .eq("provider", "xero")
    .order("connected_at", { ascending: false })
    .limit(1)
    .single();

  if (connectionError || !connection) {
    return NextResponse.json(
      { error: "No Xero connection found", details: connectionError?.message },
      { status: 404 }
    );
  }

  let accessToken = connection.access_token;

  const listUrl = `https://api.xero.com/api.xro/2.0/Invoices?where=Type=="ACCREC"`;

  let listResponse = await xeroFetch(
    listUrl,
    accessToken,
    connection.provider_tenant_id
  );

  if (listResponse.status === 401) {
    const refreshed = await refreshXeroToken(connection.refresh_token);
    accessToken = refreshed.access_token;

    await supabase
      .from("accounting_connections")
      .update({
        access_token: refreshed.access_token,
        refresh_token: refreshed.refresh_token,
        token_expires_at: new Date(
          Date.now() + Number(refreshed.expires_in || 0) * 1000
        ).toISOString(),
      })
      .eq("id", connection.id);

    listResponse = await xeroFetch(
      listUrl,
      accessToken,
      connection.provider_tenant_id
    );
  }

  if (!listResponse.ok) {
    return NextResponse.json(
      {
        error: "Xero invoice list failed",
        status: listResponse.status,
        details: await listResponse.text(),
      },
      { status: 400 }
    );
  }

  const data = await listResponse.json();
  const invoices: XeroInvoice[] = data.Invoices || [];

  const buckets = getLastCompleted12Months();
  const bucketMap = new Map<string, MonthBucket>();

  buckets.forEach((bucket) => bucketMap.set(bucket.month_key, bucket));

  let invoiceCount = 0;
  let importedLineCount = 0;

  for (const invoice of invoices) {
    if (!invoice.InvoiceID) continue;

    const detailResponse = await xeroFetch(
      `https://api.xero.com/api.xro/2.0/Invoices/${invoice.InvoiceID}`,
      accessToken,
      connection.provider_tenant_id
    );

    if (!detailResponse.ok) continue;

    const detailData = await detailResponse.json();
    const inv: XeroInvoice | undefined = detailData.Invoices?.[0];

    if (!inv) continue;
    if (inv.Type !== "ACCREC") continue;
    if (inv.Status === "VOIDED" || inv.Status === "DELETED") continue;

    const date = new Date(inv.DateString || inv.Date || "");
    const bucket = bucketMap.get(monthKey(date));

    if (!bucket) continue;

    invoiceCount += 1;

    for (const line of inv.LineItems || []) {
      const amount = Number(line.LineAmount || 0);
      const category = classifyTaxType(line.TaxType);

      bucket[category] += amount;
      importedLineCount += 1;
    }
  }

  const rollingTurnover = buckets.reduce(
    (sum, bucket) =>
      sum + bucket.standard_rated + bucket.reduced_rated + bucket.zero_rated,
    0
  );

  const percent = (rollingTurnover / VAT_THRESHOLD) * 100;

  const riskStatus =
    rollingTurnover >= VAT_THRESHOLD
      ? "Registration Required"
      : rollingTurnover >= VAT_THRESHOLD * 0.9
      ? "High Risk"
      : rollingTurnover >= VAT_THRESHOLD * 0.8
      ? "Warning"
      : "Low Risk";

  await supabase
    .from("turnover_entries")
    .delete()
    .eq("client_id", clientId)
    .eq("source", "xero");

  await supabase.from("turnover_entries").insert(
    buckets.map((bucket) => ({
      client_id: clientId,
      month_label: bucket.month_label,
      standard_rated: Number(bucket.standard_rated.toFixed(2)),
      reduced_rated: Number(bucket.reduced_rated.toFixed(2)),
      zero_rated: Number(bucket.zero_rated.toFixed(2)),
      exempt: Number(bucket.exempt.toFixed(2)),
      out_of_scope: Number(bucket.out_of_scope.toFixed(2)),
      source: "xero",
    }))
  );

  await supabase.from("vat_reviews").insert({
    client_id: clientId,
    rolling_taxable_turnover: Number(rollingTurnover.toFixed(2)),
    expected_next_30_days: 0,
    risk_status: riskStatus,
    advice_note: "Auto-imported from Xero",
  });

  let alertType: string | null = null;
  let alertMessage = "";
  let emailResult: { sent: boolean; reason: string } | null = null;

  if (percent >= 100) {
    alertType = "BREACH";
    alertMessage = "VAT threshold exceeded – registration required immediately.";
  } else if (percent >= 90) {
    alertType = "HIGH";
    alertMessage = "VAT turnover above 90% – urgent review required.";
  } else if (percent >= 80) {
    alertType = "WARNING";
    alertMessage = "VAT turnover above 80% – monitor closely.";
  }

  if (alertType) {
    await supabase.from("vat_alerts").insert({
      client_id: clientId,
      threshold_percentage: Number(percent.toFixed(2)),
      alert_type: alertType,
      message: alertMessage,
    });

    emailResult = await sendVatAlertEmail({
      clientName: client?.name || "Unknown client",
      turnover: Number(rollingTurnover.toFixed(2)),
      percent,
      alertType,
      message: alertMessage,
    });
  }

  return NextResponse.json({
    message: "Xero VAT import complete",
    clientId,
    clientName: client?.name || null,
    invoiceCount,
    importedLineCount,
    rollingTurnover: Number(rollingTurnover.toFixed(2)),
    thresholdPercent: Number(percent.toFixed(2)),
    riskStatus,
    alertType,
    emailResult,
  });
}
